name: Greet new contributors and move new issues into maintenance project

on: 
  issues:
    types: [opened]

jobs:
  add-issue-to-triage:
    name: "Add new issue to project board"
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.2.4
        with:
          project: Learning Lab Course maintenance
          column: "Triage"
          repo-token: ${{ secrets.GITHUBTEACHER_TOKEN }}

  greeting:
    name: "Greet new contributor"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
          Thanks for opening this issue!
          
          ### What happens next?
          
          One of GitHub's maintainers will triage this issue. You can help speed this up by giving us as much detail as possible in your report. If you're reporting a bug, please let us know if you can replicate it with consistency.
          
          ### Want to help?
          
          You may be able to address this issue yourself! Start by reading the [contributing guide](https://github.com/githubtraining/community-contributors/blob/main/CONTRIBUTING.md). 
